name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish Application
        run: dotnet publish -c Release -o ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: published-app
          path: ./publish

      - name: Deploy to Production Server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_PATH: /var/www/MyDotnetApp
        run: |
          set -e  # Stop execution if any command fails
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          scp -r ./publish/* $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
          ssh $SERVER_USER@$SERVER_IP << EOF
            cd $DEPLOY_PATH
            systemctl restart mydotnetapp.service
            echo "Deployment completed successfully!"
          EOF
